#!/usr/bin/env python3
"""Inspect CSI collection quality and radio metadata from a saved CSV file."""

import argparse
import csv
import pathlib
from collections import Counter

import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Inspect ESP32-S3 CSI CSV metadata and collection settings."
    )
    parser.add_argument("csv_file", help="CSV file generated by save_serial_csi.py")
    return parser.parse_args()


def as_float(value: str) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return float("nan")


def as_int(value: str) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def parse_iq_count(raw: str) -> int:
    if not raw:
        return 0
    return len(raw.split()) // 2


def describe_counter(name: str, values: list[int | str], suffix: str = "") -> None:
    counter = Counter(values)
    if not counter:
        print(f"{name}: no data")
        return
    total = sum(counter.values())
    print(f"{name}:")
    for value, count in counter.most_common():
        print(f"  {value}{suffix}: {count} frames ({count / total * 100.0:.1f}%)")


def describe_numeric(name: str, values: list[float], suffix: str = "") -> None:
    arr = np.asarray(values, dtype=np.float64)
    arr = arr[~np.isnan(arr)]
    if arr.size == 0:
        print(f"{name}: no data")
        return
    print(
        f"{name}: min {arr.min():.2f}{suffix}, "
        f"mean {arr.mean():.2f}{suffix}, max {arr.max():.2f}{suffix}"
    )


def main() -> int:
    args = parse_args()
    csv_file = pathlib.Path(args.csv_file)

    with csv_file.open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        raise SystemExit(f"No rows found in {csv_file}")

    print(f"File: {csv_file}")
    print(f"Frames: {len(rows)}")
    describe_counter("Labels", [row.get("label", "") for row in rows])
    describe_counter("Node IDs", [row.get("node_id", "") for row in rows])
    describe_counter("Source MACs", [row.get("src_mac", "") for row in rows])
    describe_counter("Destination MACs", [row.get("dst_mac", "") for row in rows])
    describe_counter(
        "First word invalid",
        [as_int(row.get("first_word_invalid", "")) for row in rows],
    )
    describe_counter("Wi-Fi primary channels", [as_int(row.get("channel", "")) for row in rows])
    describe_counter("Secondary channel field", [as_int(row.get("secondary_channel", "")) for row in rows])
    describe_counter("CSI length bytes", [as_int(row.get("csi_len", "")) for row in rows], " bytes")
    describe_counter("I/Q pairs parsed", [parse_iq_count(row.get("csi_raw_bytes", "")) for row in rows], " pairs")
    describe_counter("cwb bandwidth field", [as_int(row.get("cwb", "")) for row in rows])
    describe_counter("sig_mode field", [as_int(row.get("sig_mode", "")) for row in rows])
    describe_counter("rate field", [as_int(row.get("rate", "")) for row in rows])
    describe_counter("mcs field", [as_int(row.get("mcs", "")) for row in rows])
    describe_numeric("RSSI", [as_float(row.get("rssi", "")) for row in rows], " dBm")

    rx_seq = [as_int(row.get("rx_seq", "")) for row in rows]
    rx_seq = [value for value in rx_seq if value is not None]
    if len(rx_seq) > 1:
        gaps = sum(1 for prev, curr in zip(rx_seq, rx_seq[1:]) if curr != ((prev + 1) & 0x0FFF))
        print(f"RX sequence discontinuities: {gaps}")

    time_arr = np.asarray([as_float(row.get("local_time_us", "")) for row in rows], dtype=np.float64)
    time_arr = time_arr[~np.isnan(time_arr)]
    if time_arr.size > 1:
        dt_ms = np.diff(time_arr) / 1000.0
        dt_ms = dt_ms[dt_ms >= 0]
        if dt_ms.size > 0:
            describe_numeric("Frame interval", dt_ms.tolist(), " ms")
            mean_dt = dt_ms.mean()
            if mean_dt > 0:
                print(f"Approx. CSI frame rate: {1000.0 / mean_dt:.2f} fps")

    print()
    print("Quick interpretation:")
    print("- CSI length 128 bytes usually means 64 I/Q pairs in this project output.")
    print("- channel 1-13 means 2.4 GHz Wi-Fi; ESP32-S3 cannot use 5 GHz Wi-Fi.")
    print("- cwb=0 commonly indicates 20 MHz bandwidth; stable CSI work usually prefers 20 MHz.")
    print("- RSSI around -35 to -65 dBm is a comfortable starting range.")
    print("- If frame interval is about 1000 ms, your ping rate is too low for motion sensing.")
    print("- If first_word_invalid=1, ignore the first four raw CSI bytes during feature extraction.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
