#!/usr/bin/env python3
"""Visualize saved ESP32-S3 CSI CSV files."""

import argparse
import csv
import pathlib
from collections import Counter

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize ESP32-S3 CSI CSV data.")
    parser.add_argument("csv_file", help="CSV file generated by save_serial_csi.py")
    parser.add_argument("--out-dir", default="figures", help="Directory for generated PNG files")
    parser.add_argument("--max-frames", type=int, default=0, help="Only visualize first N frames")
    parser.add_argument(
        "--drop-zero-subcarriers",
        action="store_true",
        help="Drop subcarriers whose amplitude is always zero.",
    )
    parser.add_argument(
        "--expected-iq-pairs",
        type=int,
        default=0,
        help="Only keep frames with this many I/Q pairs. 0 means auto-detect.",
    )
    return parser.parse_args()


def parse_iq_bytes(raw: str) -> np.ndarray:
    try:
        values = np.asarray([float(token) for token in raw.split()], dtype=np.float32)
    except ValueError:
        return np.array([], dtype=np.float32)
    if values.size < 2:
        return np.array([], dtype=np.float32)
    if values.size % 2 == 1:
        values = values[:-1]
    return np.sqrt(values[0::2] * values[0::2] + values[1::2] * values[1::2])


def parse_float(raw: str) -> float | None:
    try:
        return float(raw)
    except (TypeError, ValueError):
        return None


def load_csi_csv(
    csv_file: pathlib.Path,
    max_frames: int,
    expected_iq_pairs: int,
) -> tuple[np.ndarray, np.ndarray, int, int, int]:
    amplitudes = []
    rssi_values = []
    malformed = 0

    with csv_file.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rssi = parse_float(row.get("rssi", ""))
            if row.get("type") != "CSI_DATA" or rssi is None:
                malformed += 1
                continue

            amp = parse_iq_bytes(row.get("csi_raw_bytes", ""))
            if amp.size == 0:
                malformed += 1
                continue
            amplitudes.append(amp)
            rssi_values.append(rssi)
            if max_frames > 0 and len(amplitudes) >= max_frames:
                break

    if not amplitudes:
        raise ValueError(f"No CSI frames found in {csv_file}")

    target_len = expected_iq_pairs
    if target_len <= 0:
        target_len = Counter([amp.size for amp in amplitudes]).most_common(1)[0][0]

    filtered = [
        (amp, rssi)
        for amp, rssi in zip(amplitudes, rssi_values)
        if amp.size == target_len
    ]
    if not filtered:
        raise ValueError(f"No CSI frames with {target_len} I/Q pairs found in {csv_file}")

    amp_matrix = np.vstack([amp for amp, _ in filtered])
    filtered_rssi = np.asarray([rssi for _, rssi in filtered], dtype=np.float32)
    return amp_matrix, filtered_rssi, target_len, len(amplitudes) - len(filtered), malformed


def save_heatmap(amp_matrix: np.ndarray, out_path: pathlib.Path, title: str) -> None:
    plt.figure(figsize=(12, 5))
    plt.imshow(amp_matrix.T, aspect="auto", origin="lower", interpolation="nearest")
    plt.colorbar(label="Amplitude")
    plt.xlabel("Frame index")
    plt.ylabel("Subcarrier index")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(out_path, dpi=180)
    plt.close()


def save_mean_curve(amp_matrix: np.ndarray, out_path: pathlib.Path, title: str) -> None:
    mean_amp = amp_matrix.mean(axis=1)
    diff_energy = np.abs(np.diff(amp_matrix, axis=0)).mean(axis=1)

    fig, ax1 = plt.subplots(figsize=(12, 4))
    ax1.plot(mean_amp, color="#1f77b4", linewidth=1.5, label="Mean amplitude")
    ax1.set_xlabel("Frame index")
    ax1.set_ylabel("Mean amplitude", color="#1f77b4")
    ax1.tick_params(axis="y", labelcolor="#1f77b4")

    ax2 = ax1.twinx()
    ax2.plot(np.arange(1, len(mean_amp)), diff_energy, color="#d62728", linewidth=1.2)
    ax2.set_ylabel("Difference energy", color="#d62728")
    ax2.tick_params(axis="y", labelcolor="#d62728")

    plt.title(title)
    fig.tight_layout()
    plt.savefig(out_path, dpi=180)
    plt.close(fig)


def save_rssi_curve(rssi_values: np.ndarray, out_path: pathlib.Path, title: str) -> None:
    plt.figure(figsize=(12, 3.5))
    plt.plot(rssi_values, color="#2ca02c", linewidth=1.5)
    plt.xlabel("Frame index")
    plt.ylabel("RSSI (dBm)")
    plt.title(title)
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(out_path, dpi=180)
    plt.close()


def main() -> int:
    args = parse_args()
    csv_file = pathlib.Path(args.csv_file)
    out_dir = pathlib.Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    amp_matrix, rssi_values, target_len, dropped, malformed = load_csi_csv(
        csv_file, args.max_frames, args.expected_iq_pairs
    )

    if args.drop_zero_subcarriers:
        keep = np.any(amp_matrix != 0, axis=0)
        amp_matrix = amp_matrix[:, keep]

    base = csv_file.stem
    heatmap_path = out_dir / f"{base}_amplitude_heatmap.png"
    curve_path = out_dir / f"{base}_mean_amplitude.png"
    rssi_path = out_dir / f"{base}_rssi.png"

    save_heatmap(amp_matrix, heatmap_path, f"{base} - CSI amplitude heatmap")
    save_mean_curve(amp_matrix, curve_path, f"{base} - Mean amplitude and difference")
    save_rssi_curve(rssi_values, rssi_path, f"{base} - RSSI")

    print(f"Frames: {amp_matrix.shape[0]}")
    print(f"Subcarriers/IQ pairs: {amp_matrix.shape[1]}")
    print(f"Kept I/Q pairs length: {target_len}")
    print(f"Dropped malformed/length-mismatch frames: {dropped}")
    print(f"Skipped malformed CSV rows: {malformed}")
    print(f"Saved: {heatmap_path}")
    print(f"Saved: {curve_path}")
    print(f"Saved: {rssi_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
